//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oneHourExemSpeedRun.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public Nullable<int> service { get; set; }
        public string firstname { get; set; }
        public string secondname { get; set; }
        public string lastname { get; set; }
        public Nullable<System.DateTime> dategetorder { get; set; }
    
        public virtual Service Service1 { get; set; }
    }
}
